### ISSUE TITLE
environment.bat sets up ARNOLD_DIR incorrectly. 

### ISSUE THREAD

**Issue by phtaylor** [tadevelopment/fabric2arnold#2]
currently it is...

```
SET ARNOLD_DIR=%~dp0..\..\ArnoldSDK\Windows-4.2.10.0
```

I think the line should be the following. 

```
SET ARNOLD_DIR=%~dp0exts\Fabric2Arnold
```

**Comment by FrozenKiwi** [comment]
The Arnold_Dir is a compile-time directory to find the ArnoldSDK, not the location of the Fabric extension.

It probably shouldn't be committed to git though, as I can see it would be confusing

**Comment by FrozenKiwi** [comment]
The environemt
