### ISSUE TITLE
 AiNodeGetRGBAAtString should return an RGBA values not a Color value

### ISSUE THREAD

**Issue by phtaylor** [tadevelopment/fabric2arnold#5]
RGB values are assumed to be 8 bits per channel integers. 

Color values appear to be integer values to me and in the 0-2555 range
e.g.:

```
Kd_color:RGB
   {r:119,g:121,b:66}
```

the KL math library has an 'RGBA' type:
http://docs.fabric-engine.com/FabricEngine/2.0.1/HTML/KLExtensionsGuide/Math/RGBA.kl.html

**Comment by FrozenKiwi** [comment]
RGB/RGBA colors in Arnold are represented as full 32-bit floats.  We cannot represent these colors with a lower bit-precision than the source information.

My guess is the integer values are automatically translated to floats when reading the ASS files.
