### ISSUE TITLE
AiNodeGetMatrix missing

### ISSUE THREAD

**Issue by phtaylor** [tadevelopment/fabric2arnold#7]
I am working on extracting all parameters from Arnold, so I need every method to be implemented. 
I can see it exists in the C+ api, but can't find it in the KL.

**Comment by FrozenKiwi** [comment]
The AiNodeGetMatrix function needed to be hand-translated, so its not with the other (auto-translated) functions.

You can find the function at the head of the same file though: https://github.com/tadevelopment/fabric2arnold/blob/Develop_2.0/GenKL/ai_nodes.kl#L12

**Comment by FrozenKiwi** [comment]
If you can't find a function, try searching-all for the C++ name, you will always be able to find that if it is present in the KL API.
